### ISSUE TITLE
Mic Error

### ISSUE THREAD

**Issue by haymaan** [mykle1/Hello-Lucy#1]
just install Hello-Lucy,every thing went fine,where can i change the wellkom message ... ?
thanks

**Comment by manojjenago** [comment]
Hi , I think this is one of the Cool modules for Magic Mirror. But I was wondering , if we can extend this to Voice control the Relay or GPIO pins in raspberry pi. Please guide ...
thanks
MKJ

**Comment by mykle1** [comment]
haymaan,
You can change the welcome message in the EasyPix/sound folder. Add your sound files there and enter the names in the config.js

**Comment by mykle1** [comment]
manojjenago,
That's not an issue. It's a feature request. I didn't have any more plans for Hello-Lucy but I might take a look at it again in the future
