### ISSUE TITLE
Always initialising.....

### ISSUE THREAD

**Issue by whj820228** [mykle1/Hello-Lucy#10]
Hi, very thanks for your idea !
I just follow your described steps，now ，my mic‘s icon always display “initialising”，i change debug true in MMM-voice.js,there display "initialising"and"undefined", but error.log&debug.log was nothing in it.
Can you help me , please, thank you very much!

**Comment by whj820228** [comment]
Sorry, I made a big mistake，the position: "top_center" in EasyPix module I  writed wrong，now lucy is working properly。

**Comment by mykle1** [comment]
That's great news! Enjoy your mirror
