### ISSUE TITLE
getting an error loading lucy

### ISSUE THREAD

**Issue by prithesh990** [mykle1/Hello-Lucy#12]
as it loads the mirror it shows a error in front of mic gif how to resolve that issues

**Comment by mykle1** [comment]
Run "cat /proc/asound/cards" in your terminal and verify that you have the correct microphone number in your config.js entry. If that does not work.

Open a new terminal and type these two commands:

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib (and ENTER)

sudo ldconfig (and ENTER)

I assume you installed correctly

**Comment by newasf** [comment]
I just did both these steps and still have the error. :/ I blacklisted my other audio sources to fix an issue with raspotify so I'm sure that it's using the right device. I think the issue stems from my mic being the same card and device as my speakers? (headset) Any advice would be appreciated. I can tell you more about my build but i'm new and not sure what more info would be helpful.

**Comment by mykle1** [comment]
It seems to me that you have a lot going on there. I wouldn't possibly troubleshoot all that you just described. I would only advise that you remove everything else but Lucy to see what happens. The module works as expect so I am closing the issue. If you need further assistance please create a topic on the MagicMirror forum
