### ISSUE TITLE
Adding Params

### ISSUE THREAD

**Issue by isaacrlevin** [mykle1/Hello-Lucy#13]
Given the current model, how much work would it be to add params to some of the voice commands? For instance if I wanted to open a map of a certain city and view traffic. I can figure out the Google part and changing that module, but confused on how to use mmm-voice and Lucy?

**Comment by mykle1** [comment]
Hmm, I think that has already been done (to some degree) with MMM-AssistantMk2 and GoogleMapsTraffic. The Lucy modification merely uses notifications within the framework of MM, between modules (and node_helpers). The module MMM-VoiceCommander by @TheStigh took Hello-Lucy/voice and enhanced it. It might help you determine just what is involved, or maybe it's what you are looking for. Stigh is a friend of mine. I'm sure he would be willing to give you some insight, or even help. Send him a message and tell him I sent you. :-)
