### ISSUE TITLE
AVStock not responding to commands/notifications

### ISSUE THREAD

**Issue by bazil1000** [mykle1/Hello-Lucy#14]
G'day mykle,
Thanks so much for your work on this module. Being able to control individual modules visibility is a massive help!! 
I personally am still pretty new to this so you'll need to forgive my ignorance off the bat. I've installed MM along with a good range of modules, including Hello Lucy. One module in particular, namley AVStock is however giving me grief and doesn't appear to be responding to the hide/show commands. 

Would you mind helping me with it? I've incorporated the code exactly as suggested and i can;t for the life of me work out why the module isn't responding. Also is there a way for a novice such myself to view the contents of variables in an "online / debug" mode?

**Comment by mykle1** [comment]
i think i helped you with this already on the forum. if not, open a topic there and i'll see what i can do
