### ISSUE TITLE
Installation troubles 

### ISSUE THREAD

**Issue by SSkull995** [mykle1/Hello-Lucy#16]
Hi community! 
I have a question about the installation process. I tried to install Hello Lucy on my Pi 4, which a audio card (raspiaudio mic+speaker). The problem is that when I install the module and run the MagicMirror, it asks for 2 npm packages that have not been installed before; is that right or am I doing something wrong? 
Further, after I manually install the 2 packages and the mirror starts, I can hear Lucy welcome voice but I cannot see the holo face as in Mykle video, and the microphone is not detected at all. I tried to play a music and record my voice with the card, and it works pretty well. However, Lucy does not find it at all. With arecord -l, the installed audio card shows up and, no clue why Lucy does not find it. 

Any possible idea on why this is happening? Thanks to all!!!

**Comment by mykle1** [comment]
Did you install the dependencies as per the readme file? You should not have to install anything after that.

Also, as per the installation instructions, did you determine the device numbers for your config entry?

The holo face is not part of the repo. I can give it to you but it won't work smoothly on a Pi.

Please move this to the forum where I can help you better. This is my personal repo. The community is at the forum

**Comment by SSkull995** [comment]
Hi sorry! I am going to write there then, I will post you there the answer then. Sorry!
