### ISSUE TITLE
Modules won't hide

### ISSUE THREAD

**Issue by nurd100** [mykle1/Hello-Lucy#17]
I added modules after I added Hello-Lucy, and now none of the modules will hide.

**Comment by mykle1** [comment]
Did you add the new modules to the Hello-Lucy config entry? Did you add them to the sentences array in the sentences.json file. Did you add them to the checkCommand.json file as well? Please follow all the installation instructions provided in the repo. The behavior you are describing is usually from user error. 

The most common error is when editing the checkCommands.sjon file. The very last array in the file CANNOT have a comma after it. Notice, every array has a comma after it. The last array should not.

post any errors from the console at the forum so I can see them
