### ISSUE TITLE
Question of Application [NOT AN ISSUE] 

### ISSUE THREAD

**Issue by sahullander** [mykle1/Hello-Lucy#18]
Mykle1,

First off, this is brilliant. Second off, can this be used if you run the MagicMirror in server mode (node serveronly)? If so, is Lucy listening on the host or the client device? Thanks in advance!

**Comment by mykle1** [comment]
Hello, and thank you for your kind words.

I've never tried running Lucy in server mode. I don't see any reason why it wouldn't work. There's only one way to find out, no? haha Give it a shot! :-)

Lucy will be listening on the device where she is running, I would think. The client is only "looking" at the server. As it is, you cannot interact with the server from the client or there is some real "magic" going on that I am not aware. :-)

Be well.
