### ISSUE TITLE
Integration into MK2

### ISSUE THREAD

**Issue by renzo79** [mykle1/Hello-Lucy#19]
Hello,
thanks for your work and it is an awesome eyecatcher!!

My question is more about the possibility to combine to Projects together!?

At the moment there is a lot of new stuff in the MK2 project, but the Frontend and some none Google commands are not perfect.
But especially to integrate the LUCY Frontent into the MK2 project would be really amazing.

What do you think?

Best and thx

**Comment by mykle1** [comment]
I've done a lot of work on Lucy in the past 2 years. I don't think I'll be doing any more work on her for a while. I've got a few new things that I am working on. Also, Lucy is meant to be an OFFLINE voice module and I want her to stay that way. 

Feel free to make any changes or modifications you like and thank you for your kind words.
