### ISSUE TITLE
How to activate  Module, with hello Lucy

### ISSUE THREAD

**Issue by manojjenago** [mykle1/Hello-Lucy#2]
Hi Mike,

First of all thank you for a such wonderful thing . It is really nice. 
I have set up everything as instructed , MMM-Voice has been set and then all the files has been copied. But when I say Hello Lucy it does not open the module. When I say MAGIC MIRROR which is been set at MMM-Voice it activates , then I can say hide modules or show modules. But it is also part of the MMM-Voice . Do I need to change the Keyword in config file for MMM-Voice ?? (Which I did and ended up up with mike showing error next to it , and nothing worked) .. Please guide ....... how to activate the mic with Hello Lucy keyword...
Thanks,
manoj

**Comment by mykle1** [comment]
Yes, you have to change the keyword in the config only. It should look like this 
module: 'MMM-voice',
**position: 'bottom_right',
config: {
        microphone: 0,
        keyword: 'HELLO LUCY',**

**Comment by mykle1** [comment]
If you need any more help please ask in the forums, thanks

**Comment by manojjenago** [comment]
thanks,

**Comment by varadwattamwar** [comment]
Whenever I ask lucy there is no response from him. My mic and speaker is set properly , any solutions ?? @mykle1
