### ISSUE TITLE
Request to Add New Modules

### ISSUE THREAD

**Issue by escapestudio3** [mykle1/Hello-Lucy#20]
We would like to request to have the following Modules added so Hello-Lucy can access and work with them:
-MMM-CalendarExt2
-MMM-AVStock
-MMM-lichess-daily
-MMM-Remote-Control

**Comment by mykle1** [comment]
Who's "we?" haha.  All done. Please ask requests in the forum in the future. Thanks.

Command words in the order you asked

HIDE/SHOW:

Calendar
Stocks
Chess
Remote
