### ISSUE TITLE
New Modules

### ISSUE THREAD

**Issue by jimlancey5** [mykle1/Hello-Lucy#21]
I was wondering if you would be able to set up the Hello-Lucy to be able to control the MMM-Bob-Ross module. There is no way to start the vidoes of bob ross without a module sending a notification to start the video, and I want to use Hello-Lucy to do so. Heres the link: https://github.com/Veldrovive/MMM-Bob-Ross

Sorry i sent this as an issue, I couldn't find your email to send this to you

**Comment by mykle1** [comment]
I could have Lucy broadcast a notification but you would have to edit the Bob Ross module to receive the notification and act upon that notification, unless it is already set to do that.

Please move this to the MagicMirror forum as this is a feature request
