### ISSUE TITLE
(NOT AN ERROR)

### ISSUE THREAD

**Issue by arvz108** [mykle1/Hello-Lucy#23]
Hi Mykle,
Amazing work firstly, 
I am wondering if there could be a audio reaction when the hot-word is activated.
Also I have a few Modules I will needed added if you have time I would appreciate it.

**Comment by arvz108** [comment]
Also, I viewed your video of the module running. How did you display the hologram in the mirror?

**Comment by mykle1** [comment]
Thank you for your kind words.

I don't have any plans to modify Lucy at this time. I really am rather busy with other things (and life). If you look at the files you will see where the 'audio reaction' is. You can make that addition to your own installation.

I've explained how to add modules in the readme and/or other files in the repo. Please make an honest attempt at installing them  yourself. I get bombarded with requests for help only to find that the user never actually read anything. If you have trouble after that you can reach me at the MagicMirror forum and I will troubleshoot for you there. Create a topic ex Hello-Lucy Help in the troubleshooting category.

The hologram is my MMM-EyeCandy module which is available https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules. It NOT a real hologram. It's an animated gif file. I will tell you now that a Pi will be crippled if you try to run that hologram
