### ISSUE TITLE
Adding Modules: 

### ISSUE THREAD

**Issue by Maleya** [mykle1/Hello-Lucy#24]
Hello, 
I hope this is the right place to message you, I could not see any other ways to PM via github. 
I was hoping to install Hello-Lucy on my Magic mirror but would like to have the following modules work as well: 

- 'MMM-pihole-stats',
- 'MMM-Carousel',
- 'MMM-SL-PublicTransport',
- 'MMM-CrisisInformationSweden',
- 'DailyXKCD',
- 'MMM-GameOfLife',
- 'MMM-NetworkScanner',

Where the most important ones really are SL-PublicTransport, CrisisInformationSweden. 
Thanks a ton!

**Comment by mykle1** [comment]
The directions for adding modules are in the repo. I can no longer do the additions for users because I get bombarded with requests. If you follow the directions and still have trouble you can reach me on the MagicMirror forum. I will help you there after you've made the attempt
