### ISSUE TITLE
previouslyHidden Array ? 

### ISSUE THREAD

**Issue by FinnJakobR** [mykle1/Hello-Lucy#27]
I have a Question about your previouslyHidden Array in the Hello-Lucy.js. Did I understand it right, that the Modules in this array are hidden at the startup? I tried this but it don't work for me. In my example I won't that the MMM-News Module are shown at the Startup, but when I write the Name of the Module inside the Array, its don't work and the Module is shown. Is it possible that I can only hide certain modules at the beginning and not all of them?

**Comment by mykle1** [comment]
I really don't know why you're looking inside rhe MMM-Hello-Lucy.js file at all, unless you really know what you're doing.

Only those modules named in pageOneModules of the config will show at startup. All others will be hidden. If you have made changes to any of the module files then I suggest you delete your current installation of Lucy and reinstall
