### ISSUE TITLE
HELLO LUCY DISPLAYS UNEXPECTED MODULES

### ISSUE THREAD

**Issue by Desert-Rat-Comander** [mykle1/Hello-Lucy#30]
On startup Hello Lucy displays the "currentweather" on page 1.  It is not listed on pageOne in the config.js file.  As a data point when I display a page that is defined identically to page 1,  it is not displayed.

In addition, from time to time when I issue a Show Page n,  a display of all of the Hello Lucy commands  is displayed but the module(s) on the selected page is not displayed.   The Hello Lucy commands display is full screen and the text  color is blue.

Comments/Observations:  I'm at a total loss on the firs issue.   

On the second issue,  It seems to be related to how fast I'm giving the Show Page commands .  Once I see the "Commands" screen,  I see it for all requests to Show Page n commands.  If I issue the appropriate Hide Page n commands to clear all of the Show Page n commands I issues and then wait for some time I can issue the Show Page n commands and get the expected result.

The Hello Lucy commands screen is useful,  Just not when displayed here.  Is there a way I can activate it in a page and/or print it.

Thanks for any comments or help

Desert-Rat-Commander

modules: [
		{
		disabled: false,
		module: "Hello-Lucy",
		position: "top_center",
		config: {
    			keyword: 'JARVIS',     		    // HELLO LUCY  keyword to activate listening for a command/sentence
    			timeout: 15,                        // timeout listening for a command/sentence
    			standByMethod: 'HIDE',              // 'DPMS' = anything else than RPi or 'PI'
    			microphone: "2,0",                  // run "arecord -l" card # and device # mine is "0,0"
    			sounds: ["Jarvis_At_Your_Service.mp3"],        			// "1.mp3", "11.mp3" welcome sound at startup. Add several for a random greetings
    			confirmationSound: "ok.mp3",      // name and extension of sound file
    			startHideAll: true,                 // All modules start as hidden EXCEPT PAGE ONE
    			// *** Page One is your default startup page *** This overrides startHideAll: true,
			pageOneModules:   ["Hello-Lucy","MMM-EasyPix"],               // default modules to show on page one/startup			    				
 			pageTwoModules:   ["Hello-Lucy", "clock", "MMM-BMW-OW", "alert", "calendar", "currentweather", "calendar_monthly", "MMM-Todoist"], 
			pageThreeModules: ["Hello-Lucy", "clock", "MMM-BMW-OW", "alert", "MMM-ImageSlideshow", "calendar", "currentweather", "weatherforecast", "calendar_monthly"],           // modules to show on page three
    			pageFourModules:  ["Hello-Lucy", "MMM-EasyPix"],             // modules to show on page four
    			pageFiveModules:  ["Hello-Lucy", "MMM-EasyPix"],             // modules to show on page five
    			pageSixModules:   ["Hello-Lucy", "MMM-EasyPix"],              // modules to show on page six
    			pageSevenModules: ["Hello-Lucy", "MMM-EasyPix"],            // modules to show on page seven
    			pageEightModules: ["Hello-Lucy", "MMM-EasyPix"],            // modules to show on page eight
    			pageNineModules:  ["Hello-Lucy", "MMM-EasyPix"],             // modules to show on page nine
    			pageTenModules:   ["Hello-Lucy", "MMM-EasyPix"]               // modules to show on page ten
    			}
		},

**Comment by Desert-Rat-Comander** [comment]
I've looked at all he sources I can find and do not see any other reports so I must conclude I'm doing something wrong.  I would appreciate any advice or counsel on how I should proceed to trouble shoot this issue.

**Comment by sdetweil** [comment]
current weather and weatherforcadt have a design flaw/bug. they show() themselves EVERY time they get weather data from their api. so every update interval cycle.

**Comment by Desert-Rat-Comander** [comment]
Many Thanks Sir!  Having assistance like this is outstanding and keeps rookies like me challenged to learn more and contribute in the future!
