### ISSUE TITLE
E: Package 'python-pip' has no installation candidate

### ISSUE THREAD

**Issue by HadiMirea** [mykle1/Hello-Lucy#34]
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate
[STEP 1/5] Installing Packages | Failed

when I type this command  "bash dependencies.sh"

**Comment by HadiMirea** [comment]
problem solved you need to enter to the installers file in the hello lucy module file and use python3 instead of python

**Comment by mirrormonark** [comment]
how
because not working

**Comment by sdetweil** [comment]
@mirrormonark 
```
enter to the installers file in the hello lucy module file and use python3 instead of python
```

**Comment by mirrormonark** [comment]
> @mirrormonark
> @sdetweil 
> ```
> enter to the installers file in the hello lucy module file and use python3 instead of python
> ```

I'm really grateful that someone came to my rescue.
I tried in the code line--all on the installers folder:

- python3-pip
-python-dev
-python3-is-python

always use autoremove and reboot

now... i wrote exactly this "python3 instead of python" but nothing.

In the command line. what exactly should I write in the installers folder?

THANK YOU SO MUCH LORD

**Comment by mirrormonark** [comment]
folder installers: python3 bash dependencies.sh
python3: can't open file '/home/pi/MagicMirror/modules/Hello-Lucy/installers/bash': [Errno 2] No such file or directory

**Comment by mirrormonark** [comment]
MagicMirror/modules/Hello-Lucy/installers $ python3 dependencies.sh
  File "/home/pi/MagicMirror/modules/Hello-Lucy/installers/dependencies.sh", line 12
    echo -e "\e[0m"
            ^
SyntaxError: invalid syntax

**Comment by sdetweil** [comment]
> dependencies.sh

means that is a bash file, not python 

so, EDIT the dependencies file and change python to python3
the run the bash file per the instructions

**Comment by mirrormonark** [comment]
i understand now.. and is working. AMAZING. IM VERY HAPPY my sir. now i see

 0 [Headphones     ]: bcm2835_headpho - bcm2835 Headphones
                      bcm2835 Headphones
 1 [vc4hdmi0       ]: vc4-hdmi - vc4-hdmi-0
                      vc4-hdmi-0
 2 [vc4hdmi1       ]: vc4-hdmi - vc4-hdmi-1
                      vc4-hdmi-1
 3 [Microphone     ]: USB-Audio - USB Microphone
                      MUSIC-BOOST USB Microphone at usb-0000:01:00.0-1.1, full speed
for my config is "3.0" right

**Comment by mirrormonark** [comment]
`
		{
			disabled: false,
			module: "Hello-Lucy",
			position: "top_center",
			config: {
				keyword: 'HELLO LUCY',              // keyword to activate listening for a command/sentence
				timeout: 15,                        // timeout listening for a command/sentence
				standByMethod: 'DPMS',              // 'DPMS' = anything else than RPi or 'PI'
				microphone: "3,0",                  // run "arecord -l" card # and device # mine is "0,0"
				sounds: ["1.mp3", "11.mp3"],        // welcome sound at startup. Add several for a random greetings
				confirmationSound: "ding.mp3",      // name and extension of sound file
				startHideAll: true,                 // All modules start as hidden EXCEPT PAGE ONE
				// *** Page One is your default startup page *** This overrides startHideAll: true,
				pageOneModules: ["Hello-Lucy","MMM-EasyPix"],                     // default modules to show on page one/startup
				pageTwoModules: ["Hello-Lucy", "MMM-BMW-DS", "MMM-EventHorizon"], // modules to show on page two
				pageThreeModules: ["Hello-Lucy", "MMM-Lunartic"],                 // modules to show on page three
				pageFourModules: ["Hello-Lucy", "MMM-PC-Stats"],                  // modules to show on page four
				pageFiveModules: ["Hello-Lucy", "MMM-Searchlight"],               // modules to show on page five
				pageSixModules: ["Hello-Lucy", "MMM-NOAA3"],                      // modules to show on page six
				pageSevenModules: ["Hello-Lucy", "MMM-Recipe"],                   // modules to show on page seven
				pageEightModules: ["Hello-Lucy", "MMM-rfacts"],                   // modules to show on page eight
				pageNineModules: ["Hello-Lucy", "MMM-History"],                   // modules to show on page nine
				pageTenModules: ["Hello-Lucy", "MMM-HardwareMonitor"]             // modules to show on page ten
			}
		},`

**Comment by mirrormonark** [comment]
but when start i see error in microphone..

**Comment by sdetweil** [comment]
arecord somefile.wav

speak any words 

crtl-c to stop recording

aplay somefile.wav 

do you hear what you said

**Comment by mirrormonark** [comment]
when recording.. Unsigned 8 bit, Rate 8000 Hz, Mono
but i hear my voice clear
for test i use config basic of magic mirror only basic

**Comment by mirrormonark** [comment]
file index.js

PocketSphinxContinuous.prototype.start = function() {
  if (!this.isListening()) {
    let mic=this.microphone;
    // if name starts with number
    if (this.microphone.match(/^\d/))
      mic = 'plughw:'+this.microphone;      
    this._psc = spawn('pocketsphinx_continuous', [
      '-adcdev',
      mic,
      '-inmic',
      'yes',
      '-lm',
      `modules/${this.setId}/${this.setId}.lm`,
      '-dict',
      `modules/${this.setId}/${this.setId}.dic`
    ]);

**Comment by mirrormonark** [comment]
hi. anyway it's not the module is the problem but my configuration.. then if there is a module that uses voice and makes hide and show modules and change page like this module does.. and it's updated I'll install it right away but unfortunately I haven't seen it. @sdetweil
