### ISSUE TITLE
Executing the dependencies.sh fails on step 3

### ISSUE THREAD

**Issue by roccamorice** [mykle1/Hello-Lucy#39]
After many attempts, I can't seem to get past step 2.  Installing pocketsphinx seems to fail.  

_**[STEP 3/5] Installing pocketsphinx
Cloning into 'pocketsphinx'...
remote: Enumerating objects: 17888, done.
remote: Counting objects: 100% (1719/1719), done.
remote: Compressing objects: 100% (643/643), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 6726 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
[STEP 3/5] Installing pocketsphinx | Failed**_

Does this script still work? Has anyone been successful recently with this install?

**Comment by sdetweil** [comment]
see my comment here
https://github.com/mykle1/Hello-Lucy/issues/36#issuecomment-1008437468

**Comment by roccamorice** [comment]
I did not make any changes.  After I received your comment I executed the dependencies script again (probably my 6th or 7th time) and it worked.  Strange!
