### ISSUE TITLE
no response from mic

### ISSUE THREAD

**Issue by marktillo** [mykle1/Hello-Lucy#5]
Hi Mike, any ideas why microphone doesn't pickup keyword, says ready, no issues with pocket sphinx, tried MAGIC MIRROR & HELLO LUCY, just continues to say ready, choose a mode.

![screen shot 2018-05-01 at 11 12 51](https://user-images.githubusercontent.com/32182400/39469532-a7344cd4-4d30-11e8-8f1f-df078706d68a.png)

 also what did you use for the sound files to create my own personal greeting?

**Comment by mykle1** [comment]
Keyword is set in config. When you say the keyword the mic icon and "Ready, shoose a mode" should change to a flashing icon and the word "Voice." Then you can issue commands. If it doesn't change you can try changing the microphone: number in config. 

I'd prefer if you create a topic on the forum where you can post your config. I only just saw this issue. Sorry about that
